config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::extensions(['pdf']);

Router::defaultRouteClass(DashedRoute::class);

Router::prefix('catalog', function($routes) {
  $routes->connect('/catalog', ['controller' => 'products', 'action' => 'index']);
  $routes->fallbacks(DashedRoute::class);
});

Router::prefix('admin', function($routes) {
  $routes->fallbacks(DashedRoute::class);
});

Router::scope('/', function ($routes) {
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'home']);
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    $routes->fallbacks(DashedRoute::class);
});

src/Model/Table/StocksTable.php
<?php
// src/Model/Table/StocksTable.php
namespace App\Model\Table;

use App\Utility\Converter;
use App\Utility\Formater;
use Cake\ORM\Table;
use Cake\ORM\TableRegistry;
use Cake\Validation\Validator;

class StocksTable extends Table
{

    public function initialize(array $confid)
    {
        $this->belongsTo('Users');
        $this->belongsTo('StockStatuses');

        $this->hasMany('StockProducts');
        $this->hasMany('Preproducts');
        $this->hasMany('StockPgmPricesVersion');
    }

    public function deactivateAllStocks($user_id)
    {
        $exists = $this->findByUserId($user_id)->toArray();

        if (count($exists)) {
            $this
                ->query()
                ->update()
                ->set(['active' => false])
                ->where(['user_id' => $user_id])
                ->execute();
        }
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->notEmpty('name', __('Name can not be empty'))
            ->notEmpty(['margin', 'USD_margin'], __('Margin can not be empty'))
            ->add('name', [
                'notBlank' => [
                    'rule' => 'notBlank',
                    'message' => __('Please name your stock.'),
                ],
                'unique' => [
                    'rule' => function ($value, array $context) {
                        $find = $this->find()
                            ->where([
                                'user_id' => $context['data']['user_id'],
                                'name' => trim($context['data']['name']),
                            ]);
                        return $find->count() === 0;
                    },
                    'message' => __('Stock of given name already exists'),
                ],
            ]);

        return $validator;
    }

    public function getRecentStock($user_id)
    {
        $recent_stock_id = TableRegistry::get('Users')->get($user_id)->recent_stock_id;
        $recent_stock = $this->find('all')
            ->where([
                'id' => $recent_stock_id,
            ])
            ->first();

        if (!$recent_stock) {
            return 0;
        } else {
            return $recent_stock;
        }
    }

    public function getAllUserStocks($user_id)
    {

        return $this->find('all')
            ->where([
                'user_id' => $user_id,
            ])
            ->contain([
                'StockStatuses',
            ]);
    }

    public function getAllInactiveStocks($user_id)
    {

        $inactiveStocks = $this
            ->find('all')
            ->where([
                'user_id' => $user_id,
                'active' => false,
            ]);

        return $inactiveStocks;
    }

    public function getAllStockProductsFromStock($stock_id)
    {
        $stockProducts = $this->StockProducts->find('all')
            ->where([
                'stock_id' => $stock_id,
            ])
            ->contain(['ProductVersions']);
        return $stockProducts;
    }

    public function isStockProductDeletedFromCatalog($stock_product_id)
    {

        $result = $this->StockProducts->findById($stock_product_id)
            ->contain(['ProductVersions.Products'])
            ->first()->product_version->product;

        return $result->deleted;
    }

    public function getQueryForManageUsersStock($user_id, $conditions = [])
    {
        $stock_ids = $this->getStocksIdsFromConditions($conditions);
        if ($stock_ids->count() > 0) {
            return $this->combineFullStockQueries($stock_ids, $user_id);
        }
        return $this->emptyQuery();
    }

    private function getStocksIdsFromConditions($conditions)
    {
        return $stocks = $this->find()
            ->select(['Stocks.id'])
            ->contain(['Users'])
            ->where($conditions);
    }

    private function combineFullStockQueries($stock_ids, $user_id)
    {
        $result_query = $this->query();
        $i = 0;
        foreach ($stock_ids as $stock) {
            if ($i == 0) {
                $result_query = $this->getFullStockQuery($stock->id, $user_id);
            } else {
                $query = $this->getFullStockQuery($stock->id, $user_id);
                $result_query = $result_query->unionAll($query);
            }
            $i += 1;
        }
        return $result_query;
    }

    public function emptyQuery()
    {
        return $this->findById(-1);
    }

    private function getUsersStocksBasicData($query)
    {
        $query = $query
            ->select([
                'Stocks.id',
                'Stocks.created',
                'Stocks.name',
                'Stocks.margin',
                'Stocks.USD_margin',
                'StockStatuses.name',
                'Users.first_name',
                'Users.last_name',
                'Users.email',
                'Users.id',
            ])
            ->contain(['Users', 'StockStatuses']);
        return $query;
    }

    private function getStockPricingData($stock_id)
    {
        $query = $this->find()
            ->join([
                'stock_product' => [
                    'table' => 'stock_products',
                    'type' => 'LEFT',
                    'conditions' => [
                        'stock_product.stock_id =' . $stock_id,
                    ],
                ],
                'product_version' => [
                    'table' => 'product_versions',
                    'type' => 'LEFT',
                    'conditions' => [
                        'product_version.id = stock_product.product_version_id',
                    ],
                ],
            ])
            ->where(['Stocks.id' => $stock_id]);
        return $query;
    }

    public function getFullStockQuery($stock_id, $user_id)
    {
        $query = $this->getStockQuery($stock_id);
        $query = $this->addAllFormulasToStockQuery($query, $user_id);
        $query = $this->addValuesToHedgeToFullStockQuery($query, $user_id, $stock_id);
        return $query;
    }

    private function addValuesToHedgeToFullStockQuery($query, $user_id)
    {
        $query = $this->getTestsParametersForStockProductsInFullStockQuery($query);
        foreach (['pt', 'pd', 'rh'] as $element) {
            $query = $this->addExpressionToQuery($query, $element . '_to_hedge', $this->generateValueToHedgeFormulaForElement($element));
        }
        return $query;
    }

    private function getTestsParametersForStockProductsInFullStockQuery($query)
    {
        $query = $query
            ->join([
                'product' => [
                    'table' => 'products',
                    'type' => 'LEFT',
                    'conditions' => [
                        'product.version = product_version.version',
                        'product.id = product_version.product_id',
                    ],
                ],
                'test' => [
                    'table' => 'tests',
                    'type' => 'LEFT',
                    'conditions' => [
                        'test.id = product.test_id',
                    ],
                ],
                'content_amount' => [
                    'table' => 'content_amounts',
                    'type' => 'LEFT',
                    'conditions' => [
                        'stock_product.content_amount_id = content_amount.id',
                    ],
                ],
            ]);
        return $query;
    }

    private function generateValueToHedgeFormulaForElement($element)
    {
        return 'stock_product.no_of_pcs * test.' . $element . ' * content_amount.value * 0.8';
    }

    private function getStockQuery($stock_id)
    {

        $query = $this->getStockPricingData($stock_id);
        $query = $this->getUsersStocksBasicData($query);

        return $query;
    }

    private function addAllFormulasToStockQuery($query, $user_id)
    {
        $formula_generators = $this->getGeneratingMethods();
        $exchange_rate = $this->Users->getUserExchangeRate($user_id);
        foreach ($formula_generators as $generator) {
            $query = $this->addExpressionToQuery($query, $this->getGeneratorParamName($generator), $this->{$generator}($exchange_rate));
        }
        return $query;
    }

    private function addExpressionToQuery($query, $param_name, $formula)
    {
        return $query->select([$param_name => $query->newExpr()->add($formula)]);
    }

    private function getGeneratingMethods()
    {
        $methods = get_class_methods($this);
        $result = [];
        foreach ($methods as $method) {
            if (substr($method, 0, 10) == '_generate_') {
                $result[] = $method;
            }
        }
        return $result;
    }

    private function getGeneratorParamName($generator_name)
    {
        $arr = explode('__', $generator_name);
        return $arr[1];
    }

    private function roundFormula($formula)
    {
        return 'CAST( (' . $formula . ') AS DECIMAL(10,2))';
    }

    private function multiplyFormula($col_name, $value)
    {
        return '(' . $col_name . '*' . $value . ')';
    }

    private function generateSumOfValuesFormula($col_name, $exchange_rate = 1)
    {
        $formula = 'SUM( ' . $col_name . ' * ' . $exchange_rate . ')';
        return $formula;
    }

    private function generateAveragePerPcFormula($formula)
    {
        $formula = $this->divideFormulas($formula, $this->_generate__total_count__Formula());
        return $this->roundFormula($formula);
    }

    private function generateAveragePerKgFormula($formula)
    {
        $formula = $this->divideFormulas($formula, $this->_generate__total_weight__Formula());
        return $this->roundFormula($formula);
    }

    private function divideFormulas($formula1, $formula2)
    {
        return '(' . $formula1 . ')/' . '(' . $formula2 . ')';
    }

    private function _generate__total_count__Formula($exchange_rate = 1)
    {

src/Template/Element/stock_index/create_stock_modal.ctp
<div class="modal create-modal" id="create-stock-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-title">
                    <?=h(__('Create new stock'))?>
                </div>
            </div>
            <div class="modal-body">
                <?=$this->Form->create($new_stock, ['url' => ['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'create'], 'id' => 'create-stock-form'])?>
                <div class="row">
                    <div class="col-md-12">
                        <?=$this->Form->control('name', ['label' => __('Name'), 'type' => 'text']);?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?=$this->element('units/text_input', ['field_name' => 'margin', 'unit' => $this->Units->percent(), 'other_props' => ['label' => __('Margin'), 'placeholder' => '0.00']])?>
                    </div>
                    <div class="col-md-6">
                        <?=$this->element('units/text_input', ['field_name' => 'USD_margin', 'unit' => $this->Units->getCurrencySymbol($user_currency_code), 'other_props' => ['label' => __('Margin'), 'placeholder' => '0.00']])?>
                    </div>
                </div>
                <div class="row submit-row">
                    <div class="col-md-12">
                        <div class="btn-group float-right" style="height: 36px;">
                            <input type="submit" name="submit" class="btn submit-btn" value="<?=h(__('Save'))?>">
                            <button class="cancel-btn" data-dismiss="modal"><?=h(__('Cancel'))?></button>
                        </div>
                    </div>
                </div>
                <?=$this->Form->end()?>
            </div>
        </div>
    </div>
</div>

src/Template/Element/stock_index/stock_index_header.ctp
<div class="row header-row justify-content-center align-items-center">
    <div class="header-col col-md-4">
        <p class="header stock-header"><?=h(__('STOCK STATUS') . ': ')?><span class="value"><?=h($stock->stock_status->name)?></span></p>
    </div>
    <div class="header-col col-md-4">
        <p class="header stock-header"><?=h(__('SHOWING STOCK') . ': ')?><span class="value"><?=h($stock->name)?></span></p>
    </div>
    <div class="header-col col-md-4">
        <div class="btn-group float-right my-btn-group">
            <button id="create-stock-btn" data-toggle="modal" data-backdrop="static" data-keyboard="false"
                data-target="#create-stock-modal">
                <span id="create-new-stock-full-text"><?=h(__('Create new stock'))?></span>
                <span id="create-new-stock-small-res"><?=h(__('Create'))?></span>
            </button>
        </div>
    </div>
</div>
<div class="margin-15"></div>

<div class="btn-group my-btn-group">
    <?php if ($stocks): ?>
    <div class="dropdown">
        <button class="dropdown-btn btn-grey dropdown-toggle" id="dropdown-select-stock" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <?=h(__('Select stock'))?><img src="/img/stock_icons/icon-arrow-down.png">
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdown-select-stock">
            <?php foreach ($stocks as $stock_item): ?>
            <a class="dropdown-item"
                href="<?=$this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'select', $stock_item->id])?>">
                <?=h($stock_item->name)?>
            </a>
            <?php endforeach;?>
        </div>
    </div>
    <?php endif;?>
    <?php if ($stock->id): ?>
    <?php if ($stock_open): ?>
    <button class="common-btn small-square" data-toggle="modal" data-backdrop="static" data-keyboard="false"
        data-target="#refresh-stock-modal"><img
            src="/img/stock_icons/icon-refresh.png"><?=h(__('Refresh'))?>
    </button>
    <button class="common-btn small-square" data-toggle="modal" data-backdrop="static" data-keyboard="false"
        data-target="#delete-stock-modal"><img
            src="/img/stock_icons/icon-remove-stock.png"><?=h(__('Remove stock'))?>
    </button>
    <button class="common-btn small-square" data-toggle="modal"
        data-backdrop="static" data-keyboard="false" data-target="#close-stock-modal">
        <?=h(__('Close'))?>
    </button>
    <?php elseif ($stock_closed): ?>
        <button class="common-btn small-square" data-toggle="modal"
            data-backdrop="static" data-keyboard="false" data-target="#cancel-stock-modal">
            <?=h(__('Cancel'))?>
        </button>
    <?php elseif ($stock_cancelled || $stock_rejected): ?>
        <button class="common-btn small-square"
            onclick="location.href='<?=$this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'reopen', $stock->id])?>';">
                <?=h(__('Re-open'))?>
        </button>
    <?php endif;?>
    <button class="common-btn small-square"
        onclick="location.href='<?=$this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'export', $stock->id])?>';"><img
            src="/img/stock_icons/icon-export.png"><?=h(__('Export to PDF'))?>
    </button>
    <button class="common-btn small-square"
        onclick="location.href='<?=$this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'summary', $stock->id])?>';">
        <?=h(__('Stock stats'))?>
    </button>
    <?php endif;?>
    <?php if ($stock->id): ?>
    <div class="dropdown">
        <div class="dropdown-menu" aria-labelledby="dropdown-change-stock-status">
            <?php foreach ($stock_statuses as $stock_status): ?>
            <a class="dropdown-item"
                href="<?=$this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'changeStatus', $stock->id, $stock_status])?>">
                <?=h($stock_status)?>
            </a>
            <?php endforeach;?>
        </div>
    </div>
    <?php endif;?>
</div>

<?=$this->element('/stock_index/create_stock_modal')?>
<?=$this->element('confirm_modal', ['modal_id' => 'refresh-stock-modal', 'modal_title' => __('Refresh stock'), 'modal_message' => __('Are you sure? This operation is irreversible.'), 'confirm_action_url' => $this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'refresh', $stock->id]), 'confirm_button_text' => __('Refresh')])?>
<?=$this->element('confirm_modal', ['modal_id' => 'delete-stock-modal', 'modal_title' => __('Delete stock'), 'modal_message' => __('Are you sure? This operation is irreversible.'), 'confirm_action_url' => $this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'removeStock', $stock->id]), 'confirm_button_text' => __('Delete')])?>
<?=$this->element('confirm_modal', ['modal_id' => 'close-stock-modal', 'modal_title' => __('Close stock'), 'modal_message' => __('Request to admin will be send, and you will be no longer able to edit this stock. Are you sure?'), 'confirm_action_url' => $this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'close', $stock->id]), 'confirm_button_text' => __('Close stock')])?>
<?=$this->element('confirm_modal', ['modal_id' => 'cancel-stock-modal', 'modal_title' => __('Cancel stock'), 'modal_message' => __('Request to admin will be withdraw. Are you sure?'), 'confirm_action_url' => $this->Url->build(['prefix' => 'catalog', 'controller' => 'stocks', 'action' => 'cancel', $stock->id]), 'confirm_button_text' => __('Cancel stock')])?>